package com.bpm.audit.model;

public enum OperationType {
    PROCESS_START,
    PROCESS_CANCEL,
    PROCESS_COMPLETE,
    TASK_APPROVE,
    TASK_REJECT,
    TASK_RETURN,
    TASK_RETURN_INITIATOR,
    TASK_DELEGATE,
    TASK_REASSIGN,
    TASK_COUNTERSIGN,
    TASK_COMMENT,
    TASK_CLAIM,
    TASK_URGE,
    FORM_SUBMIT,
    FORM_UPDATE,
    BPMN_DEPLOY,
    EXTERNAL_API_CALL,
    DATA_ACCESS,
    CONFIG_CHANGE,
    EXPORT_DATA
}
